version: '3.7'

services:
  drawer:
    build: ./Dockerfile
    ports:
      - 8085:80
    volumes:
      - ./drawer:/var/www/html
  sorter:
    build: ./Dockerfile
    ports:
      - 8086:80
    volumes:
      - ./sorter:/var/www/html
  inf_adm:
    build: ./Dockerfile
    ports:
      - 8087:80
    volumes:
      - ./inf_adm:/var/www/html
